import Logo from "@/components/atoms/Logo";
import Paragraph from "@/components/atoms/Paragraph";
import React from "react";

const Colaboration = () => {
  return (
    <div className="px-20 py-20 flex flex-col gap-20">
      <div className="text-center">
        <Paragraph
          className="text-[black] text-[42px]"
          text="Mitra Asuransi Terpercaya"
        />
        <Paragraph
          className="text-[gray] !text-[18px]"
          text="Lebih dari 40 perusahaan asuransi terkemuka dan terpercaya telah bermitra dengan Fuse dan membantu spesialis asuransi kami menyediakan berbagai produk asuransi untuk memenuhi kebutuhan perlindungan Customer."
        />
      </div>
      <div className="flex flex-col gap-10">
        <div className="flex justify-around">
          <Logo
            img={
              <img
                width={200}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/simas_insurtech.svg.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={120}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/AIA_logo.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={100}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/tugu.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={120}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/mega.png"
              />
            }
          />
        </div>
        <div className="flex justify-around">
          <Logo
            img={
              <img
                width={150}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/Sompo-1536x502.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={100}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/etiqa.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={110}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/MSIG.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={200}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/artarindo.png"
              />
            }
          />
        </div>
        <div className="flex justify-around">
          <Logo
            img={
              <img
                width={120}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/seainsure-1536x451.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={100}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/HARTA.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={110}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/Avrist-logo-1536x468.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={150}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/zurich.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={100}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/sequis.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={200}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/lippoinsurance.png"
              />
            }
          />
        </div>
        <div className="flex justify-around">
          <Logo
            img={
              <img
                width={100}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/NowHealth_Logo_Global.jpg"
              />
            }
          />
          <Logo
            img={
              <img
                width={100}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/Great-Eastern-1536x595.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={100}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/bni-life.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={80}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/generali-logo.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={100}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/oona-insurance.jpg"
              />
            }
          />
          <Logo
            img={
              <img
                width={80}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/aia-logo-618BFE8E96-seeklogo.com_.png"
              />
            }
          />
        </div>
        <div className="flex justify-around">
          <Logo
            img={
              <img
                width={150}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/Candi-Insurance-1536x384.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={150}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/mag.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={150}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/starinvestama.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={120}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/simasjiwa.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={100}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/car-2.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={120}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/Astra-Life-1536x537.png"
              />
            }
          />
        </div>
        <div className="flex justify-center gap-40 items-center">
          <Logo
            img={
              <img
                width={80}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/April-International.jpg"
              />
            }
          />
          <Logo
            img={
              <img
                width={100}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/FWD.png"
              />
            }
          />
          <Logo
            img={
              <img
                width={120}
                height={100}
                src="https://brokerindotekno.co.id/wp-content/uploads/2023/05/Aetna-logo-1536x896.jpg"
              />
            }
          />
        </div>
      </div>
    </div>
  );
};

export default Colaboration;
